# Generated by Django 5.1.6 on 2025-03-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportAreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tg_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SportAreaImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sport_area_images/')),
                ('sport_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sportareamodel')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('sport_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='app.sportareamodel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_area', to='app.sessionareamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
    ]
