# Generated by Django 5.1.6 on 2025-03-04 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportAreaImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sport_area_images/')),
                ('sport_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sportareamodel')),
            ],
        ),
    ]
