# Generated by Django 5.1.7 on 2025-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
