# Generated by Django 5.1.7 on 2025-03-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
