# Generated by Django 5.1.7 on 2025-03-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usermodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
