# Generated by Django 5.1.6 on 2025-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sportareaimagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportareamodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
