# Generated by Django 5.1.6 on 2025-03-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sportareamodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionareamodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
