# Generated by Django 5.1.6 on 2025-03-04 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sessionareamodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='session_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_area', to='app.sessionareamodel'),
        ),
    ]
