# Generated by Django 5.1.6 on 2025-03-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_user_id_usermodel_user_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionareamodel',
            name='data',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='sessionareamodel',
            name='sport_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='app.sportareamodel'),
        ),
    ]
